version: '3.5'

services:
  influxdb:
    build:
      context: ./docker/influxdb
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/influxdb:latest
    hostname: influxdb
    ports:
      - '8086:8086'

  grafana:
    build:
      context: ./docker/grafana
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/grafana:latest
    links:
      - influxdb
      - telegraf
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    hostname: grafana

  rtspserver:
    build:
      context: ./docker/simplertsp
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/simplertspserver:latest
    ports:
      - '8554:8554'
      - '8888:8888'

  mosquittoserver:
    build:
      context: ./docker/mosquitto
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/mosquitto:latest.5
    ports:
      - '1883:1883'
      - '9001:9001'

  opcua:
    build:
      context: ./docker/opcua
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/opcuaserver:latest
    hostname: opcuaserver
    ports:
      - '4840:4840'

  telegraf:
    build:
      context: ./docker/telegraf
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/telegraf:latest
    restart: on-failure
    links:
      - opcua
      - mosquittoserver
    depends_on:
      - influxdb
      - opcua
      - mosquittoserver
    ports:
      - '5100:5100'

  industrial-safety:
    build:
      context: docker/openvino
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/industrial-safety:latest
    restart: on-failure
    container_name: industrial-safety
    ports:
      - '5000:5000'
    depends_on:
      - rtspserver
      - mosquittoserver
      - influxdb
      - opcua