version: '3.5'

services:
  influxdb:
    build:
      context: modules/influxdb
      dockerfile: Dockerfile.influxdb
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/influxdb:latest
    hostname: influxdb
    ports:
      - '8086:8086'

  grafana:
    build:
      context: modules/grafana
      dockerfile: Dockerfile.grafana
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/grafana:latest
    links:
      - influxdb
      - telegraf
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    hostname: grafana

  simplertspserver:
    build:
      context: modules/simplertsp
      dockerfile: Dockerfile.simplertsp
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/simplertspserver:latest
    ports:
      - '8554:8554'
      - '8888:8888'

  mosquittoserver:
    build:
      context: modules/mosquitto
      dockerfile: Dockerfile.mosquitto
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/mosquitto:latest
    ports:
      - '1883:1883'
      - '9001:9001'

  opcua:
    build:
      context: modules/opcua
      dockerfile: Dockerfile.opcua
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/opcuaserver:latest
    hostname: opcuaserver
    ports:
      - '4840:4840'

  telegraf:
    build:
      context: modules/telegraf
      dockerfile: Dockerfile.telegraf
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/telegraf:latest
    restart: on-failure
    links:
      - opcua
      - mosquittoserver
    depends_on:
      - influxdb
      - opcua
      - mosquittoserver
    ports:
      - '5100:5100'

  industrial-safety:
    build:
      context: modules/industrial-safety
      dockerfile: Dockerfile.openvino
    image: industrialsafetyanddefectdetectionregistry.azurecr.io/industrial-safety:latest
    restart: on-failure
    container_name: industrial-safety
    environment:
      - DEFECT_TARGET_HARDWARE=$DEFECT_TARGET_HARDWARE
      - IOTHUB_DEVICE_DPS_ENDPOINT=$IOTHUB_DEVICE_DPS_ENDPOINT
      - IOTHUB_DEVICE_DPS_ID_SCOPE=$IOTHUB_DEVICE_DPS_ID_SCOPE
      - IOTHUB_DEVICE_DPS_DEVICE_ID=$IOTHUB_DEVICE_DPS_DEVICE_ID
      - IOTHUB_DEVICE_DPS_DEVICE_KEY=$IOTHUB_DEVICE_DPS_DEVICE_KEY
    ports:
      - '5000:5000'
    depends_on:
      - simplertspserver
      - mosquittoserver
      - influxdb
      - opcua