version: '3.5'

services:
  influxdb:
    build:
      context: ./docker/influxdb
    image: inteliscwestcontainerregistry.azurecr.io/influxdb:latest.5
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_BUCKET=Industrial_Detection_Safety
      - DOCKER_INFLUXDB_INIT_ORG=acmeindustries
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=defect_tracking
    ports:
      - '8086:8086'

  grafana:
    build:
      context: ./docker/grafana
    environment:
      - GF_PANELS_DISABLE_SANITIZE_HTML=true
      - GF_INSTALL_PLUGINS=agenty-flowcharting-panel
    image: inteliscwestcontainerregistry.azurecr.io/grafana:latest.5
    links:
      - influxdb
      - telegraf
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    hostname: grafana

  rtspserver:
    build:
      context: ./docker/simplertsp
    image: inteliscwestcontainerregistry.azurecr.io/simplertspserver:latest.5
    ports:
      - '8554:8554'
      - '8888:8888'

  mosquittoserver:
    build:
      context: ./docker/mosquitto
    image: inteliscwestcontainerregistry.azurecr.io/mosquitto:latest.5
    ports:
      - '1883:1883'
      - '9001:9001'

  opcua:
    build:
      context: ./docker/opcua
    image: opcuaserver
    hostname: opcuaserver
    ports:
      - '4840:4840'

  telegraf:
    build:
      context: ./docker/telegraf
    image: telegraf
    restart: on-failure
    links:
      - opcua
      - mosquittoserver
    depends_on:
      - influxdb
      - opcua
      - mosquittoserver
    ports:
      - '5100:5100'

  industrial-safety:
    build:
      context: docker/openvino
    image: industrial-safety
    restart: on-failure
    container_name: industrial-safety
    ports:
      - '5000:5000'
    depends_on:
      - rtspserver
      - mosquittoserver
      - influxdb
      - opcua